# google cloud build
# gcloud beta builds submit --config cloudbuild-base.yml --region=us-west3 --substitutions=COMMIT_SHA=$(git rev-parse --short HEAD) --project=fluid-417204 .
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "--no-cache",
        "-t",
        "us-west3-docker.pkg.dev/${PROJECT_ID}/${_APP_REPOSITORY}/${_APP_NAME}-rails/web:base",
        ".",
        "-f",
        "docker/Dockerfile.base",
      ]
    id: build

  - name: gcr.io/cloud-builders/docker
    args:
      [
        "tag",
        "us-west3-docker.pkg.dev/${PROJECT_ID}/${_APP_REPOSITORY}/${_APP_NAME}-rails/web:base",
      ]
    id: Tag

  - name: gcr.io/cloud-builders/docker
    args:
      [
        "push",
        "us-west3-docker.pkg.dev/${PROJECT_ID}/${_APP_REPOSITORY}/${_APP_NAME}-rails/web:base",
      ]
    id: push base

substitutions:
  _APP_NAME: "fluid-droplet-shipstation"
  _APP_REPOSITORY: "fluid-droplets"

images:
  - "us-west3-docker.pkg.dev/${PROJECT_ID}/${_APP_REPOSITORY}/${_APP_NAME}-rails/web:base"

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
