/**
 * Active Record Encryption, reimplemented for the Next app.
 *
 * `IntegrationSetting` declares `encrypts :settings, deterministic: true`, so
 * `integration_settings.settings` does NOT hold the credentials as JSON. It
 * holds Active Record's message envelope:
 *
 *     { "p": "<base64 ciphertext>", "h": { "iv": "…", "at": "…", "c"?: true } }
 *
 * The Rails app is still the deployed one and both apps run against the same
 * row, so this app has to read and write that exact envelope — anything else
 * either can't read an existing company's ShipStation credentials, or writes a
 * value Rails then fails to decrypt. Reimplementing it is the only option that
 * keeps a migration reversible.
 *
 * Faithful to ActiveRecord::Encryption as of Rails 8:
 *
 *  - key   = PBKDF2-HMAC-<digest>(secret, key_derivation_salt, 2**16, 32 bytes)
 *            <digest> is SHA256 under `config.load_defaults 7.1` or later, which
 *            config/application.rb sets to 8.0. It is SHA1 for an app still on
 *            6.1 defaults. This is NOT a detail to guess at: deriving with the
 *            wrong digest yields a valid-looking 32-byte key that fails GCM
 *            authentication on every row, which is exactly how this app went to
 *            production able to reach the database and unable to read a single
 *            company's credentials (STU2-3293). Decryption therefore tries
 *            SHA256 and then SHA1, and reports which answered.
 *  - iv    = HMAC-SHA256(key, clear_text)[0, 12] for deterministic attributes
 *  - cipher= AES-256-GCM, empty auth_data, 16-byte auth tag
 *  - bodies over 140 bytes are raw-deflated first and tagged `"c": true`
 *
 * The 140-byte threshold is not a tuning knob: it decides whether a message is
 * compressed at all, and Rails picked it so a deterministic message stays stable
 * for a given clear text.
 *
 * One limit worth knowing. Below the threshold this produces bytes IDENTICAL to
 * Ruby's, which the tests pin. Above it, the ciphertext covers a DEFLATE stream,
 * and DEFLATE output depends on the zlib build — Ruby's differs from Node's, and
 * Linux's differs from macOS's. So a long value written here is fully readable by
 * Rails (inflate accepts any valid stream) but is not the same bytes Rails would
 * have written. That only matters for a `where(settings: …)` equality lookup, and
 * neither app does one.
 *
 * Verified against Rails 8.1.3.1 output — see encrypted-attribute.test.ts,
 * whose vectors were generated by ActiveRecord::Encryption itself.
 */

import {
  createCipheriv,
  createDecipheriv,
  createHmac,
  pbkdf2Sync,
} from "node:crypto";
import { deflateSync, inflateSync } from "node:zlib";

const CIPHER = "aes-256-gcm";
const IV_LENGTH = 12;
const KEY_LENGTH = 32;
const AUTH_TAG_LENGTH = 16;
const PBKDF2_ITERATIONS = 2 ** 16;
/** ActiveRecord::Encryption::Encryptor::THRESHOLD_TO_JUSTIFY_COMPRESSION. */
const COMPRESSION_THRESHOLD = 140;

/** The `{p, h}` envelope Rails writes into the column. */
export interface EncryptedMessage {
  p: string;
  h: { iv: string; at: string; c?: boolean };
}

export class RailsEncryptionError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "RailsEncryptionError";
  }
}

/**
 * Reads the Active Record Encryption keys from the environment.
 *
 * The same three variables config/application.rb reads, so a deployment that
 * already runs Rails needs no new secrets. Missing keys throw rather than
 * defaulting: a default here would silently write ciphertext Rails cannot read.
 */
function encryptionKey(digest: KeyDigest = "sha256"): Buffer {
  const secret = process.env.ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY;
  const salt = process.env.ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT;

  if (!secret || !salt) {
    throw new RailsEncryptionError(
      "ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY and " +
        "ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT must be set — they are " +
        "the keys the Rails app already uses for integration_settings.settings",
    );
  }

  return deriveKey(secret, salt, digest);
}

/**
 * The digests an Active Record app could have derived with, newest first.
 *
 * Rails 7.1 changed `active_record.encryption.hash_digest_class` from SHA1 to
 * SHA256 in its new framework defaults. config/application.rb declares
 * `config.load_defaults 8.0`, so the running Rails app derives with SHA256 and
 * everything in `integration_settings` was written under it.
 */
export const KEY_DIGESTS = ["sha256", "sha1"] as const;
export type KeyDigest = (typeof KEY_DIGESTS)[number];

/** Exposed for the test vectors; the app always goes through encryptionKey(). */
export function deriveKey(
  secret: string,
  salt: string,
  digest: KeyDigest = "sha256",
): Buffer {
  return pbkdf2Sync(secret, salt, PBKDF2_ITERATIONS, KEY_LENGTH, digest);
}

function deterministicIv(key: Buffer, clearText: Buffer): Buffer {
  return createHmac("sha256", key).update(clearText).digest().subarray(0, IV_LENGTH);
}

/** Encrypts a string into Rails' envelope, deterministically. */
export function encryptMessage(plaintext: string, key = encryptionKey()): EncryptedMessage {
  const raw = Buffer.from(plaintext, "utf8");
  const compressed = raw.byteLength > COMPRESSION_THRESHOLD;
  // Rails compresses BEFORE deriving the iv, so the iv covers the bytes that
  // are actually encrypted.
  const body = compressed ? deflateSync(raw) : raw;

  const iv = deterministicIv(key, body);
  const cipher = createCipheriv(CIPHER, key, iv, { authTagLength: AUTH_TAG_LENGTH });
  cipher.setAAD(Buffer.alloc(0));
  const payload = Buffer.concat([cipher.update(body), cipher.final()]);

  const headers: EncryptedMessage["h"] = {
    iv: iv.toString("base64"),
    at: cipher.getAuthTag().toString("base64"),
  };
  if (compressed) headers.c = true;

  return { p: payload.toString("base64"), h: headers };
}

/** Decrypts one of Rails' envelopes back to the string it was built from. */
export function decryptMessage(message: EncryptedMessage, key?: Buffer): string {
  const authTag = Buffer.from(message.h.at, "base64");
  // Truncated tags are forgeable, and Ruby's OpenSSL bindings do not reject
  // them — Rails checks the length itself, so this does too. Checked once,
  // before any key is tried: it is a property of the message, not of the key.
  if (authTag.byteLength !== AUTH_TAG_LENGTH) {
    throw new RailsEncryptionError("encrypted message has a truncated auth tag");
  }

  // An explicit key means the caller has already chosen a derivation.
  if (key) return decryptWith(message, key, authTag);

  // Otherwise try each derivation the app could be running against. GCM
  // authenticates, so a wrong key cannot produce a plausible plaintext — it
  // throws. Trying SHA1 after SHA256 costs one failed decrypt on an app that
  // has never used SHA1, and is what lets this read rows written before a
  // `load_defaults` bump without a migration.
  let lastError: unknown;
  for (const digest of KEY_DIGESTS) {
    try {
      return decryptWith(message, encryptionKey(digest), authTag);
    } catch (error) {
      lastError = error;
    }
  }
  throw lastError instanceof Error
    ? lastError
    : new RailsEncryptionError(String(lastError));
}

function decryptWith(
  message: EncryptedMessage,
  key: Buffer,
  authTag: Buffer,
): string {
  const decipher = createDecipheriv(
    CIPHER,
    key,
    Buffer.from(message.h.iv, "base64"),
    { authTagLength: AUTH_TAG_LENGTH },
  );
  decipher.setAuthTag(authTag);
  decipher.setAAD(Buffer.alloc(0));

  const payload = Buffer.from(message.p, "base64");
  const plain = Buffer.concat([decipher.update(payload), decipher.final()]);

  return (message.h.c ? inflateSync(plain) : plain).toString("utf8");
}

/** True when a column value looks like an Active Record Encryption envelope. */
export function isEncryptedMessage(value: unknown): value is EncryptedMessage {
  if (!value || typeof value !== "object") return false;
  const record = value as Record<string, unknown>;
  const headers = record.h as Record<string, unknown> | undefined;
  return (
    typeof record.p === "string" &&
    !!headers &&
    typeof headers === "object" &&
    typeof headers.iv === "string" &&
    typeof headers.at === "string"
  );
}
