default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: droplet_shipstation_development

test:
  <<: *default
  database: droplet_shipstation_test

production:
  primary:
    <<: *default
    database: droplet_shipstation_production
    url: <%= ENV['DATABASE_URL'] %>
  cache:
    <<: *default
    database: droplet_shipstation_production_cache
    migrations_paths: db/cable_migrate
    url: <%= ENV['CACHE_DATABASE_URL'] %>
  queue:
    <<: *default
    database: droplet_shipstation_production_queue
    migrations_paths: db/queue_migrate
    url: <%= ENV['QUEUE_DATABASE_URL'] %>
  cable:
    <<: *default
    database: droplet_shipstation_production_cable
    migrations_paths: db/cable_migrate
    url: <%= ENV['CABLE_DATABASE_URL'] %>
